name: build-on-windows-msbuild-x64

on:
  push:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Install choco packages
      run: |
        choco install unzip
    - name: Install perl prerequisites
      run: |
        perl -S cpan App::cpanminus
        perl -S cpanm App::Prove Capture::Tiny Clone CPU::Z80::Assembler Data::Dump Data::HexDump File::Path List::Uniq Modern::Perl Object::Tiny::RW Regexp::Common Test::Harness Text::Diff Text::Table YAML::Tiny
    - name: Checkout from git
      uses: actions/checkout@v3
      with: 
        submodules: 'true'
    - name: Get lastest nightly
      run: |
        curl -L -o z88dk-win32-latest.zip http://nightly.z88dk.org/z88dk-win32-latest.zip
        unzip -d win32-latest z88dk-win32-latest.zip
    - name: Find MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: Create config.h
      run: |
        call win32\config\make_config.cmd
    - name: Build for Debug
      run: |
        msbuild win32\z88dk.sln -t:rebuild -verbosity:diag -property:Platform=x64 -property:Configuration=Debug
    - name: Build for Release
      run: |
        msbuild win32\z88dk.sln -t:rebuild -verbosity:diag -property:Platform=x64 -property:Configuration=Release
    - name: Copy files from nightly
      run: |
        copy /y bin\z88dk-z80asm.exe src\z80asm\
        copy /y win32-latest\z88dk\lib\z88dk-z80asm*.lib src\z80asm\
        copy /y win32-latest\z88dk\lib\clibs\*.lib lib\clibs\
        copy /y win32-latest\z88dk\bin\z88dk-zsdcc.exe bin\
        copy /y win32-latest\z88dk\bin\m4.exe bin\
        copy /y win32-latest\z88dk\libsrc\_DEVELOPMENT\lib\sccz80\*.lib libsrc\_DEVELOPMENT\lib\sccz80\
        copy /y win32-latest\z88dk\libsrc\_DEVELOPMENT\lib\sdcc_ix\*.lib libsrc\_DEVELOPMENT\lib\sdcc_ix\
        copy /y win32-latest\z88dk\libsrc\_DEVELOPMENT\lib\sdcc_iy\*.lib libsrc\_DEVELOPMENT\lib\sdcc_iy\
    - name: Run z80asm tests
      run: |
        cd src\z80asm
        set PATH=%RUNNER_WORKSPACE%\z88dk\bin;%PATH%
        set ZCCCFG=%RUNNER_WORKSPACE%\z88dk\lib\config
        perl -S prove t\*.t
