name: z88dk

on:
  push:
    branches: [ ** ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'true'
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/.ccache
          ~/perl5
        key: ${{ runner.os }}-cache
    - name: Install apt dependencies
      run: sudo apt install -y dos2unix libboost-all-dev texinfo texi2html gdb curl cpanminus ccache libmodern-perl-perl libtemplate-perl ragel libyaml-perl
    - name: Install perl prerequisites
      run: cpanm --local-lib=~/perl5 local::lib App::Prove Modern::Perl Capture::Tiny Capture::Tiny::Extended Path::Tiny File::Path Template Template::Plugin::YAML Test::Differences Text::Table CPU::Z80::Assembler Test::Cmd::Common Test::HexDifferences Data::HexDump Object::Tiny::RW Regexp::Common List::Uniq Clone
    - name: Perl setup
      run: eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
    - name: Build binaries
      run: ./build.sh -l
    - name: Build libraries
      run: ./build.sh -b
    - name: Build examples
      run: ./build.sh -b -l -e
    - name: Build tests
      run: ./build.sh -b -l -t
